import groovy.json.JsonSlurper

plugins {
	id 'base'
	id 'fabric-loom' version "${loom_version}" apply false
	id 'maven-publish'
}

version = project.mod_version
group = project.maven_group

def configuredVersions = (new JsonSlurper().parseText(file('settings.json').text).versions ?: []) as List<String>

tasks.register('buildAndGather') {
	configuredVersions.each { versionName ->
		dependsOn ":${versionName}:build"
	}

	doFirst {
		println 'Gathering builds'
		def rootBuildLibs = file('build/libs')
		delete fileTree(rootBuildLibs) {
			include '*'
		}

		configuredVersions.each { versionName ->
			copy {
				from(file("versions/${versionName}/build/libs")) {
					include '*.jar'
					exclude '*-dev.jar', '*-sources.jar'
				}
				into rootBuildLibs
				duplicatesStrategy DuplicatesStrategy.INCLUDE
			}
		}
	}
}

tasks.named('build') {
	dependsOn tasks.named('buildAndGather')
}
