import groovy.json.JsonSlurper

pluginManagement {
	repositories {
		maven {
			name = 'AliyunPublic'
			url = 'https://maven.aliyun.com/repository/public'
		}
		maven {
			name = 'AliyunGradlePlugin'
			url = 'https://maven.aliyun.com/repository/gradle-plugin'
		}
		maven {
			name = 'BMCLAPI'
			url = 'https://bmclapi2.bangbang93.com/maven/'
		}
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

def settings = new JsonSlurper().parseText(file('settings.json').text)
for (String version : settings.versions) {
	include(":$version")

	def proj = project(":$version")
	proj.projectDir = file("versions/$version")
	proj.buildFileName = "../../common.gradle"
}
